### ISSUE TITLE
Python Injection

### ISSUE THREAD

**Issue by KronosDesign** [wibiti/evedec#10]
Great tool, thanks for sharing this.
Wondering if you have any insight on injection methods though?
I stumbled upon lolpy4 but it seems quite outdated.
Any help would be greatly appreciated.

**Comment by wibiti** [comment]
I haven't done it in a while. One obvious change is that the method
shouldn't inject 32bit code now that Eve is 64bit.

**Comment by KronosDesign** [comment]
Turns out I was overcomplicating things and it's as simple as a single call to the interpreter internally.
Thanks for your reply anyway.
