### ISSUE TITLE
some file faild

### ISSUE THREAD

**Issue by bbday** [wibiti/evedec#4]
With last eve version there are some problem with some py file that faild 
(# decompiled 5258 files: 5148 okay, 110 failed) 
with this error:
Syntax error at or near `POP_BLOCK' token at offset 705

Thanks for your work.

**Comment by wibiti** [comment]
Confirmed. Looks like the bytecode compilation of while 1 may have changed.

**Comment by wibiti** [comment]
Apparently there was a just a POP_BLOCK added into the while1 bytecode, so I expanded the grammar in uncompyle2 to include that possibility. Seems to have fixed the problem.
