### ISSUE TITLE
Failed to decompile

### ISSUE THREAD

**Issue by bbday** [wibiti/evedec#7]
### Can't decompile E:\eve-17.01.1448074\fsdBuiltData\common\base.py

 Others files are ok (# decompiled 5539 files: 5538 okay, 1 failed)

**Comment by aploium** [comment]
same problem

**Comment by aploium** [comment]
and this is my `blue.dll` and `fsdBuiltData\common\base.py`

[base.pyj.zip](https://github.com/wibiti/evedec/files/3058797/base.pyj.zip)

[blue.zip](https://github.com/wibiti/evedec/files/3058799/blue.zip)

**Comment by wibiti** [comment]
I think all files decompile now with the last change I made to scanner.py in uncompyle2.
https://github.com/wibiti/uncompyle2/commit/ed7f22eb6537b27688fdf3722d1c2e73fdbd7cde
