### ISSUE TITLE
Key failed. Attempting key switch.

### ISSUE THREAD

**Issue by wanjizheng** [wibiti/evedec#8]
Hi, after the latest upgrade (14/07/2020), this doesn't work anymore.  Most likely it is because they've changed the decryption key in the blue.dll file.  Since this application search that information automatically, then most likely they have changed the blob_header.  Anyway, the error message shows below: 

Number of possible keys found: 1

[                     SIMPLEBLOB (as found in blue.dll)                         ]
[    publickeystruc   ]
[type ver  res  alg_id] [alg_id] [                encryptedkey                  ]
   01  02 0000 00006603 0000a400 8591b55b371557ae6b802f57d38391522089c47a08b064ba

[         PLAINTEXTKEYBLOB (converted from above simpleblob for import)            ]
[          hdr        ]
[type ver  res  alg_id] [dwKeySize] [                  rgbKeyData                  ]
   08  02 0000 00006603    00000018 ba64b0087ac48920529183d3572f806bae5715375bb59185

Key failed. Attempting key switch.
!!! All keys failed. Exiting.

**Comment by wibiti** [comment]
Thanks for letting me know.
I took a look at it. The problem is actually that the files are not
encrypted anymore, so trying to decrypt them just trashes them.
