### ISSUE TITLE
No keys found in blue.dll

### ISSUE THREAD

**Issue by strich** [wibiti/evedec#9]
I imagine this project is now dead but I thought I'd ask anyway - Seems the script can no longer find any decryption keys in the dll. CCP changed how they do things now?

**Comment by wibiti** [comment]
It still mostly works for me. My output looks like: 

Number of possible keys found: 1

[                     SIMPLEBLOB (as found in blue.dll)                         ]
[    publickeystruc   ]
[type ver  res  alg_id] [alg_id] [                encryptedkey                  ]
   01  02 0000 00006603 0000a400 8591b55b371557ae6b802f57d38391522089c47a08b064ba

[         PLAINTEXTKEYBLOB (converted from above simpleblob for import)            ]
[          hdr        ]
[type ver  res  alg_id] [dwKeySize] [                  rgbKeyData                  ]
   08  02 0000 00006603    00000018 ba64b0087ac48920529183d3572f806bae5715375bb59185

Key failed. Attempting key switch.
Attempting decompress without decryption.
+++ Okay decompiling C:\eve-18.09.1820316\__init__.py
+++ Okay decompiling C:\eve-18.09.1820316\ccp_exceptions.py
+++ Okay decompiling C:\eve-18.09.1820316\AutoIndexer.py
...
+++ Okay decompiling C:\Users\wbtii\eve-18.09.1820316\eve\devtools\script\svc_slash.py
+++ Okay decompiling C:\Users\wbtii\eve-18.09.1820316\eve\devtools\script\uiDebugger.py
+++ Okay decompiling C:\Users\wbtii\eve-18.09.1820316\eve\devtools\script\tournamentRefereeTools.py
# decompiled 6454 files: 6453 okay, 1 failed
# elapsed time: 0:03:23.599000

**Comment by strich** [comment]
I must have the wrong directories setup?
```
[main]
eve_path = C:\Program Files (x86)\Steam\steamapps\common\Eve Online\SharedCache\tq\
store_path = ..\
```
![image](https://user-images.githubusercontent.com/987896/95806997-d496d200-0d54-11eb-98ee-b97c134f03fd.png)

**Comment by wibiti** [comment]
I'll just remove all the decryption code, since the files aren't encrypted anymore. Then it won't even need to look for blue.dll.

**Comment by strich** [comment]
Well that makes things easier hah!

Thanks for keeping this up to date.
